### ISSUE TITLE
tickets are spent, points are written, but the balance does not change

### ISSUE THREAD

**Issue by antofaka** [akasakaid/blumtod#101]
![1](https://github.com/user-attachments/assets/54587b04-e2d0-4a16-a7f0-6e6e9cad62ac)

**Comment by akasakaid** [comment]
I don't know. I haven't updated so it should be an error if you enable auto play games.

**Comment by shrif3llam** [comment]
> I don't know. I haven't updated so it should be an error if you enable auto play games.

when will you update ?!

**Comment by Erkinovich-fx** [comment]
> ![1](https://private-user-images.githubusercontent.com/26692917/377297387-54587b04-e2d0-4a16-a7f0-6e6e9cad62ac.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NzUyODIsIm5iZiI6MTcyOTc3NDk4MiwicGF0aCI6Ii8yNjY5MjkxNy8zNzcyOTczODctNTQ1ODdiMDQtZTJkMC00YTE2LWE3ZjAtNmU2ZTljYWQ2MmFjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDEzMDMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNDE1ODI3MzE4MzYyN2U3NzFjNzViYWEyYmI2YjAyZTk0YmE5MGJlMzgwMWNlZDRkNjk2ODE0YTNjMDQ4NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SmN7ive0y7Ib36xXjl_JVn_LQNrxrx6VUiirgUXwytQ)

I need this code bro can u share it

**Comment by malvere** [comment]
Seems like Blum changed the way they handle payload for /claim endpoint
Now they use encoded endpoint that seems to be encrypted (decoding with base64 gave no results)
I'll provide example below:

```json
{
  "payload": "DaCO6D97EJV4hxlad1pIkml6/NLSvaVBRygIDXyVKCXkqd4AyFV4bOIbW6gd9wteeINOTDDEaLTy3oBFOZtKKwAM1wAWf8y1xEBBFqmmnC214xV6zIIgEuc0NYKjvTJaSJ/jb9rs+tZGhRk/goVM3pphpx5j8447UR5e/MO6lC2uo3trqozosDeVrz40FfyBNSc6kTlSOOFvDp9LV53j2tBx5ys9cBnQ8VmHeJG+ioqdmIbwhwFtAVNrUsqn3MpWXMFYH0K/bdPXzhV+0o7VQgGj9LHe1KO5FIFkVtWuFzJUuofSZoiVNvrTOVE8Jm+DdvTnso/gTHM0Nvq/QCi9FQbEP9iZmZ9HgTra8NSBxPwE03SdLMFjf8Lokmf1JUYYuNZnlQDzVfLOsui0CQnLq3EeZ1C/+9jmhD4VaiDu4eAUQ4iyCvMTieKUWbWV9wxeIfrJ9PRCkI2hIcDmF9DoRHthUO0AujHA7uhgAutDqJRxO06a/4e6pTJJuo/Rvp/igZEjnfcxy1dohFADl4/RFpyC8opsWP6UHQ57rEXqwIwkTg9ZhOKa18EQ25HTNiLbW2r9J+Vl5OmlRy+7QbquXFd4zyVpVY+wikQVb1t5sO8Jh/ZiRmNKaJ/CNNK3bPPjXWZVuQFRueJHNM4KzTK/uiS/ANDXfuFgrZTLxriolvo="
}
```
