### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by djcobra** [akasakaid/blumtod#102]
hi there,Can you help me?Please
when i run the bot 
[20:01:25]-[acc 1] already check in today !
[20:01:26]-[acc 1] balance : 38083.5
[20:01:27]-[acc 1] referral balance : 0
[20:01:27]-[acc 1] you have 761 game ticket
Traceback (most recent call last):
  File "C:\Users\Sinno\blumtod\bot.py", line 622, in <module>
    asyncio.run(main())
    ~~~~~~~~~~
  File "C:\Program Files\Python313\Lib\json\decoder.py", line 362, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Can you tell me what's wrong and how to fix it? thx!!

**Comment by marksofox1** [comment]
same problem

**Comment by bomber8338** [comment]
> hi there,Can you help me?Please
> when i run the bot 
> [20:01:25]-[acc 1] already check in today !
> [20:01:26]-[acc 1] balance : 38083.5
> [20:01:27]-[acc 1] referral balance : 0
> [20:01:27]-[acc 1] you have 761 game ticket
> Traceback (most recent call last):
>   File "C:\Users\Sinno\blumtod\bot.py", line 622, in <module>
>     asyncio.run(main())
>     ~~~~~~~~~~
>   File "C:\Program Files\Python313\Lib\json\decoder.py", line 362, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> Can you tell me what's wrong and how to fix it? thx!!
Same problem
I don't know why ???

**Comment by Rezerveq** [comment]
![Screenshot_20241020-191637](https://github.com/user-attachments/assets/62036292-d875-41ab-9c11-90bb07e4537f)

**Comment by LuiisFernando** [comment]
same error here
