### ISSUE TITLE
After 30s of starting the game.

### ISSUE THREAD

**Issue by JJJ562004** [akasakaid/blumtod#11]
After 30s when the game start, I got this issue. Can you help me?
![image](https://github.com/user-attachments/assets/51261904-4ab2-4946-9ab7-6b82fe0cb2e5)

**Comment by akasakaid** [comment]
> After 30s when the game start, I got this issue. Can you help me?
> ![image](https://github.com/user-attachments/assets/51261904-4ab2-4946-9ab7-6b82fe0cb2e5)
> 

See content of file http.log

**Comment by akasakaid** [comment]
Send screenshot here

**Comment by akasakaid** [comment]
I already fix this error. `git pull` to get latest versino

**Comment by JJJ562004** [comment]
> I already fix this error. `git pull` to get latest versino

Thanks, and sorry for the late reply, it works now
