### ISSUE TITLE
Question about multiple accounts

### ISSUE THREAD

**Issue by 284267** [akasakaid/blumtod#15]
Hello, I am trying to allow two accounts. After I imported the second information, I ran the script to execute the first account, and then it kept pausing at this point without executing the task for the next account. What is the reason?
![image](https://github.com/user-attachments/assets/7e228478-c1f3-4cbd-8b81-cfb0074964f6)

**Comment by akasakaid** [comment]
> Hello, I am trying to allow two accounts. After I imported the second information, I ran the script to execute the first account, and then it kept pausing at this point without executing the task for the next account. What is the reason?
> ![image](https://github.com/user-attachments/assets/7e228478-c1f3-4cbd-8b81-cfb0074964f6)
> 

Re run the script
