### ISSUE TITLE
After the waiting until countdown ends, will the script be executed from account 1 to the last account?

### ISSUE THREAD

**Issue by 284267** [akasakaid/blumtod#17]
![image](https://github.com/user-attachments/assets/9b9d7bb7-ccca-47f1-8247-fd53ba85de50)
After the waiting until countdown ends, will the script be executed from account 1 to the last account?

**Comment by FarmTon** [comment]
yes, you can check the iteration inside bot.py

**Comment by 284267** [comment]
I don't quite understand, I still need to learn. Thank you for your answer.
