### ISSUE TITLE
I can not get Data

### ISSUE THREAD

**Issue by MrTimonM** [akasakaid/blumtod#19]
I clicked F12 and nothing happens in Blum APP
I right click in the app too, it did not work. Inspect element did not show up. 

Help please.
I tried on desktop. 
Telegram Official app and 64Gram

**Comment by OrrnobMahmud** [comment]
you enabled web inspecting from telegram setting first?

**Comment by MrTimonM** [comment]
> you enabled web inspecting from telegram setting first?

I did and I got it. Thanks anyways
