### ISSUE TITLE
Please Fix this

### ISSUE THREAD

**Issue by yourbee03** [akasakaid/blumtod#21]
![photo_2024-09-05_21-56-58](https://github.com/user-attachments/assets/4e7e1ffa-8048-4bc3-862a-0c3e41b6b723)

**Comment by antofaka** [comment]
i have some problem, script dont work.

**Comment by anandaaptana** [comment]
problems that also happened to me, please fix it immediately

**Comment by anandaaptana** [comment]
Thx!

**Comment by yjr18100553** [comment]
脚本失灵了。
