### ISSUE TITLE
无法自动签到门票

### ISSUE THREAD

**Issue by 284267** [akasakaid/blumtod#23]
请修复

**Comment by 284267** [comment]
![image](https://github.com/user-attachments/assets/bdc9a3e6-f8c3-4b7d-a728-1a747ed77fe3)

**Comment by akasakaid** [comment]
修复了什么？

**Comment by 284267** [comment]
I&nbsp;found&nbsp;that&nbsp;the&nbsp;code&nbsp;can't&nbsp;sign&nbsp;in&nbsp;every&nbsp;day&nbsp;to&nbsp;get&nbsp;tickets.&nbsp;Can&nbsp;this&nbsp;problem&nbsp;be&nbsp;fixed?

杉树久藏
***@***.***




---原始邮件---
发件人: &quot;Fawwaz ***@***.***&gt;
发送时间: 2024年9月6日(周五) 中午11:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [akasakaid/blumtod] 无法自动签到门票 (Issue #23)




 
修复了什么？
 
&mdash;

**Comment by akasakaid** [comment]
What? please reply in github web or app.

**Comment by 284267** [comment]
Okay!&nbsp;Wait&nbsp;for&nbsp;my&nbsp;reply&nbsp;this&nbsp;afternoon.

杉树久藏
***@***.***




---原始邮件---
发件人: &quot;Fawwaz ***@***.***&gt;
发送时间: 2024年9月6日(周五) 中午12:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [akasakaid/blumtod] 无法自动签到门票 (Issue #23)




 
What? please reply in github web or app.
 
&mdash;

**Comment by 284267** [comment]
When I enter the Blum game for the first time every day, this picture interface will be displayed. I can click continue to collect several tickets and play games to get points. The code does not execute the function of automatically collecting tickets every day. I don’t know whether the code does not have this function or I did something wrong.
![image](https://github.com/user-attachments/assets/2bde6970-f0e8-42c5-a08e-eeed66c1bbcf)
![image](https://github.com/user-attachments/assets/c1420520-5dc7-4355-804c-8af327377ef5)
