### ISSUE TITLE
wrong

### ISSUE THREAD

**Issue by 2780qq** [akasakaid/blumtod#24]
![c00ff6e2c39faa2f933ae91cdbb5f14](https://github.com/user-attachments/assets/743c876b-11b6-4b0b-a812-d5091d8e0dff)

**Comment by 2780qq** [comment]
这是为什么

**Comment by HoangREALER** [comment]
Find `https://gateway.blum.codes/v1/auth/provider/PROVIDER_TELEGRAM_MINI_APP` and change it to
`https://user-domain.blum.codes/api/v1/auth/provider/PROVIDER_TELEGRAM_MINI_APP`

**Comment by akasakaid** [comment]
what the hellllll, try to git pull dude. the code already update it.

**Comment by HoangREALER** [comment]
Sheeeesh, did not realize, LOL.

**Comment by joepeak** [comment]
> what the hellllll, try to git pull dude. the code already update it.

如何加入你的团队，我也想贡献代码

**Comment by joepeak** [comment]
> Find `https://gateway.blum.codes/v1/auth/provider/PROVIDER_TELEGRAM_MINI_APP` and change it to `https://user-domain.blum.codes/api/v1/auth/provider/PROVIDER_TELEGRAM_MINI_APP`

请问这个连接是怎么找到的，我尝试了好久，都没有发现原来是连接变了
