### ISSUE TITLE
Failed fetch json and failed checkin and failed get task list

### ISSUE THREAD

**Issue by MeninSun** [akasakaid/blumtod#30]
![image](https://github.com/user-attachments/assets/68d17e29-3095-4ce2-9ee0-c6fc781a90d8)

how to solve that? sometimes error like that is appear

**Comment by Ntxfloy** [comment]
I have the same problem, but I can't start spending tickets at all.
![image](https://github.com/user-attachments/assets/09dce179-a8a9-4a3c-a947-62357da08cbf)

**Comment by MeninSun** [comment]
> I have the same problem, but I can't start spending tickets at all. ![image](https://private-user-images.githubusercontent.com/73457065/367232765-09dce179-a8a9-4a3c-a947-62357da08cbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMjk1NTEsIm5iZiI6MTcyNjIyOTI1MSwicGF0aCI6Ii83MzQ1NzA2NS8zNjcyMzI3NjUtMDlkY2UxNzktYThhOS00YTNjLWE5NDctNjIzNTdkYTA4Y2JmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDEyMDczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MjRiN2M0Y2EwNzAzMmU5NGQ2MGYxZGRiOTcyMzZmODA4ZmI2MmEyOWNkMDUwZGM1MmQxZjYyMjI0M2EzMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8T5PIOhxDAXm2r8dRzJsUcbLygmpZzIOD5k72pZ4Jzs)



> I have the same problem, but I can't start spending tickets at all. ![image](https://private-user-images.githubusercontent.com/73457065/367232765-09dce179-a8a9-4a3c-a947-62357da08cbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMjk1NTEsIm5iZiI6MTcyNjIyOTI1MSwicGF0aCI6Ii83MzQ1NzA2NS8zNjcyMzI3NjUtMDlkY2UxNzktYThhOS00YTNjLWE5NDctNjIzNTdkYTA4Y2JmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDEyMDczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MjRiN2M0Y2EwNzAzMmU5NGQ2MGYxZGRiOTcyMzZmODA4ZmI2MmEyOWNkMDUwZGM1MmQxZjYyMjI0M2EzMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8T5PIOhxDAXm2r8dRzJsUcbLygmpZzIOD5k72pZ4Jzs)

me too, sometimes it happen

**Comment by akasakaid** [comment]
For the failed fetch json response problem, I haven't fixed it yet but for the solve task problem, I fixed it yesterday. Update your script.

**Comment by MeninSun** [comment]
Thanks a lot, for your great work.
