### ISSUE TITLE
It seems that the proxy cannot be used successfully. The data displayed at the end, "country: region: city:", is still my own local data instead of the one set in proxies.txt.

### ISSUE THREAD

**Issue by Zhangxiaokang123** [akasakaid/blumtod#32]
It seems that the proxy cannot be used successfully. The data displayed at the end, "country: region: city:", is still my own local data instead of the one set in proxies.txt.

**Comment by akasakaid** [comment]
Show me the contents of your proxies.txt.

**Comment by Zhangxiaokang123** [comment]
![1111](https://github.com/user-attachments/assets/75ea29e0-9609-47ac-81fd-1bca9ab60b85)
I have tried socks5 and http.

**Comment by Zhangxiaokang123** [comment]
> 请向我显示你的 proxies.txt 的内容。

![1111](https://github.com/user-attachments/assets/f8b52eec-0f0f-484d-ad3a-643621818e9c)
I have tried socks5 and http.

**Comment by akasakaid** [comment]
The format you entered is wrong, look at the image you provided. 'socks5h' is the wrong format, the correct one is 'socks5://'

> > 请向我显示你的 proxies.txt 的内容。
> 
> ![1111](https://private-user-images.githubusercontent.com/86096237/367480296-f8b52eec-0f0f-484d-ad3a-643621818e9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyODAyOTUsIm5iZiI6MTcyNjI3OTk5NSwicGF0aCI6Ii84NjA5NjIzNy8zNjc0ODAyOTYtZjhiNTJlZWMtMGYwZi00ODRkLWFkM2EtNjQzNjIxODE4ZTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDAyMTMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MTVmOTRhM2Q2YTFhZDJlYThiZGNlOGE5NzAyMzFjODE3MDMyNzk5MDdmNTI5OTMyZTUwZTc3MGNmNzY0NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hxiIL4foO4umBx78NmefalDkP3qSZkq75JGDe1y-1KA) I have tried socks5 and http.

**Comment by Zhangxiaokang123** [comment]
> 您输入的格式错误，请查看您提供的图片。'socks5h' 格式错误，正确的格式是 'socks5://'
> 
> > > 请向我显示您的 proxy.txt 的内容。
> > 
> > 
> > ![1111](https://private-user-images.githubusercontent.com/86096237/367480296-f8b52eec-0f0f-484d-ad3a-643621818e9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyODAyOTUsIm5iZiI6MTcyNjI3OTk5NSwicGF0aCI6Ii84NjA5NjIzNy8zNjc0ODAyOTYtZjhiNTJlZWMtMGYwZi00ODRkLWFkM2EtNjQzNjIxODE4ZTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDAyMTMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MTVmOTRhM2Q2YTFhZDJlYThiZGNlOGE5NzAyMzFjODE3MDMyNzk5MDdmNTI5OTMyZTUwZTc3MGNmNzY0NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hxiIL4foO4umBx78NmefalDkP3qSZkq75JGDe1y-1KA)我已经尝试过 socks5 和 http。
I have tried them all. Socks5 didn't work before, so I sought help online and used sockes5h, but it didn't work. The proxy information still showed local.

**Comment by Zhangxiaokang123** [comment]
> > 您输入的格式错误，请查看您提供的图片。'socks5h' 格式错误，正确的格式是 'socks5://'
> > > > 请向我显示您的 proxy.txt 的内容。
> > > 
> > > 
> > > ![1111](https://private-user-images.githubusercontent.com/86096237/367480296-f8b52eec-0f0f-484d-ad3a-643621818e9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyODAyOTUsIm5iZiI6MTcyNjI3OTk5NSwicGF0aCI6Ii84NjA5NjIzNy8zNjc0ODAyOTYtZjhiNTJlZWMtMGYwZi00ODRkLWFkM2EtNjQzNjIxODE4ZTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDAyMTMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MTVmOTRhM2Q2YTFhZDJlYThiZGNlOGE5NzAyMzFjODE3MDMyNzk5MDdmNTI5OTMyZTUwZTc3MGNmNzY0NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hxiIL4foO4umBx78NmefalDkP3qSZkq75JGDe1y-1KA)我已经尝试过 socks5 和 http。
> > > 都试过了，之前 socks5 不行，于是上网求助，用了 sockes5h，还是不行，代理信息还是显示本地。

You can help me try it.

**Comment by Zhangxiaokang123** [comment]
Still can't solve this problem

**Comment by zclsx** [comment]
i also have this question bro

**Comment by Zhangxiaokang123** [comment]
> i also have this question bro

I see that the responses returned by session.get are all local proxies, and the ones in proxies.txt are not used, although the assignment is successful.

**Comment by zclsx** [comment]
> > 我也有这个问题兄弟
> 
> 我看到session.get返回的响应都是本地代理，而proxies.txt中的响应没有使用，虽然分配成功了。

me too, i think the data and proxy need a common file ,it can ps: 3token share one ip

**Comment by Zhangxiaokang123** [comment]
I don’t know how to solve this problem and successfully use the proxy in this proxies.txt, blogger help me!!!

**Comment by BlessedUzama** [comment]
Am also having this problem, have tried different ways and it still didn't work.

**Comment by Zhangxiaokang123** [comment]
> Am also having this problem, have tried different ways and it still didn't work.

So I don't know if the proxy has taken effect.

**Comment by Zhangxiaokang123** [comment]
> I already re write to new http library, check new version.

Can it run successfully without using a proxy? I keep getting an error message "network error!" when using a proxy, but other scripts can run normally, so it may not be my network problem. Could you please check it?

**Comment by akasakaid** [comment]
> > I already re write to new http library, check new version.
> 
> Can it run successfully without using a proxy? I keep getting an error message "network error!" when using a proxy, but other scripts can run normally, so it may not be my network problem. Could you please check it?

I've actually never experienced that while using proxies, I'll check later.
