### ISSUE TITLE
Support for secret code

### ISSUE THREAD

**Issue by penpinz** [akasakaid/blumtod#39]
Automate the secret code tasks by allowing us to enter once and store it in the script .

**Comment by akasakaid** [comment]
> Automate the secret code tasks by allowing us to enter once and store it in the script .

I have created a github page for the task verification code.

**Comment by akasakaid** [comment]
> Automate the secret code tasks by allowing us to enter once and store it in the script .

I have created a github page for the task verification code.

**Comment by penpinz** [comment]
Your script automatically fetch the answers from the page?

**Comment by penpinz** [comment]
Thanks mate
