### ISSUE TITLE
Same time login is an issue please set previous way check and complete all account one after another next one. 

### ISSUE THREAD

**Issue by Softexdigitalbd** [akasakaid/blumtod#40]
New bot logged in same time in simultaneously  in parallel which not good who do not use proxy . Previously it was one after another , completing first account then go for second one , now present update  it logged in same time from different account it may cause ip ban or account ban

**Comment by akasakaid** [comment]
Read https://github.com/akasakaid/blumtod?tab=readme-ov-file#command-line-options--arguments worker usage section.
