### ISSUE TITLE
Unable to run 24 hours.

### ISSUE THREAD

**Issue by 284267** [akasakaid/blumtod#45]
![image](https://github.com/user-attachments/assets/c62acba5-727c-4611-ade4-14955da6678e)
Displays this, unable to resolve.

**Comment by akasakaid** [comment]
use screen to run 24/7.

**Comment by 284267** [comment]
I&nbsp;solved&nbsp;this&nbsp;problem,

杉树久藏
***@***.***




---Original---
From: &quot;Fawwaz ***@***.***&gt;
Date: Sat, Sep 21, 2024 08:59 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [akasakaid/blumtod] Unable to run 24 hours. (Issue #45)




 
use screen to run 24/7.
 
&mdash;
