### ISSUE TITLE
Can't Solve Auto Task 

### ISSUE THREAD

**Issue by hzdf114** [akasakaid/blumtod#47]
I use my account and switch auto task on, then when I checked on http.log the response is 400 and no task have done, please check the screenshot below 
![Screenshot 2024-09-21 120717](https://github.com/user-attachments/assets/18070f66-3526-4d90-beda-e29e8b47b369)

**Comment by groovg** [comment]
I have the same issue on multiple accounts as well

**Comment by akasakaid** [comment]
> I use my account and switch auto task on, then when I checked on http.log the response is 400 and no task have done, please check the screenshot below 
> ![Screenshot 2024-09-21 120717](https://github.com/user-attachments/assets/18070f66-3526-4d90-beda-e29e8b47b369)
> 

There are indeed some tasks that cannot be completed by bot scripts because they require interaction with others. So that is not a problem.

**Comment by groovg** [comment]
> > I use my account and switch auto task on, then when I checked on http.log the response is 400 and no task have done, please check the screenshot below
> > ![Screenshot 2024-09-21 120717](https://private-user-images.githubusercontent.com/179069875/369596713-18070f66-3526-4d90-beda-e29e8b47b369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5ODk4NTcsIm5iZiI6MTcyNjk4OTU1NywicGF0aCI6Ii8xNzkwNjk4NzUvMzY5NTk2NzEzLTE4MDcwZjY2LTM1MjYtNGQ5MC1iZWRhLWUyOWU4YjQ3YjM2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQwNzE5MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjNjNmVlMDdlNTFlMTY1ZTgxYTg4ZWRlYTZmYWI1N2Y2NWM3OGE2YWJlNWJlNDBmNzY2NjAxNTY4ZDVmMTUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2fvWIuJDfnmybo9HS3OyiLFWmpRuV-tXF5jmafDAotU)
> 
> There are indeed some tasks that cannot be completed by bot scripts because they require interaction with others. So that is not a problem.

Bot doesn't do any task, even easiest ones. I have some account that are like that, any task cannot be completed

**Comment by akasakaid** [comment]
> > > I use my account and switch auto task on, then when I checked on http.log the response is 400 and no task have done, please check the screenshot below
> > > ![Screenshot 2024-09-21 120717](https://private-user-images.githubusercontent.com/179069875/369596713-18070f66-3526-4d90-beda-e29e8b47b369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5ODk4NTcsIm5iZiI6MTcyNjk4OTU1NywicGF0aCI6Ii8xNzkwNjk4NzUvMzY5NTk2NzEzLTE4MDcwZjY2LTM1MjYtNGQ5MC1iZWRhLWUyOWU4YjQ3YjM2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQwNzE5MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjNjNmVlMDdlNTFlMTY1ZTgxYTg4ZWRlYTZmYWI1N2Y2NWM3OGE2YWJlNWJlNDBmNzY2NjAxNTY4ZDVmMTUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2fvWIuJDfnmybo9HS3OyiLFWmpRuV-tXF5jmafDAotU)
> > 
> > 
> > There are indeed some tasks that cannot be completed by bot scripts because they require interaction with others. So that is not a problem.
> 
> Bot doesn't do any task, even easiest ones. I have some account that are like that, any task cannot be completed

You can disable auto solve task feature.
