### ISSUE TITLE
RuntimeError('Event loop is closed')

### ISSUE THREAD

**Issue by DrewzPhoenix** [akasakaid/blumtod#49]
I use my account to run  start bot (multiprocessing) but always getting RuntimeError('Event loop is closed'). I don't know what went wrong. Pls help me! Thank you
![Screenshot_1](https://github.com/user-attachments/assets/3ee34534-04cd-4af6-86c5-781c6c829c4d)

**Comment by akasakaid** [comment]
Try to use option number 6
