### ISSUE TITLE
daily check error

### ISSUE THREAD

**Issue by Bruder55x** [akasakaid/blumtod#5]
does not claim daily check rewards

**Comment by akasakaid** [comment]
> does not claim daily check rewards

Really? Send the screenshot

**Comment by Bruder55x** [comment]
code says already check in today

**Comment by akasakaid** [comment]
> code says already check in today but not

Try to wait until next claim time.

**Comment by Bruder55x** [comment]
now is worked.I guess it didn't work because you tried it in the early hours.
