### ISSUE TITLE
invalid scheme component 

### ISSUE THREAD

**Issue by nguyenanh29** [akasakaid/blumtod#50]
![image](https://github.com/user-attachments/assets/d5a6a474-4e6d-4605-9872-62a699a0ad01)

**Comment by akasakaid** [comment]
Check your proxy format sir, i think you write wrong format.

**Comment by nguyenanh29** [comment]
I set the format of previous version of your bot. After i do git pull, it comes put with those errors. Have you update proxy format?

**Comment by nguyenanh29** [comment]
> Check your proxy format sir, i think you write wrong format.

Found it. Thanks for prompt response sir!
