### ISSUE TITLE
Can't get useragent

### ISSUE THREAD

**Issue by vanhbakaa** [akasakaid/blumtod#55]
![Screenshots_2024-09-25-23-50-28](https://github.com/user-attachments/assets/6120ed35-a3f0-4aa5-a63d-06bd22b98502)

**Comment by akasakaid** [comment]
> ![Screenshots_2024-09-25-23-50-28](https://github.com/user-attachments/assets/6120ed35-a3f0-4aa5-a63d-06bd22b98502)
> 

Read how to update section in readme.
