### ISSUE TITLE
\models.py", line 76, in get_by_id     "useragent": result["useragent"],                  ~~~~~~^^^^^^^^^^^^^ IndexError: No item with that key

### ISSUE THREAD

**Issue by fastnfuriousbd** [akasakaid/blumtod#56]
\models.py", line 76, in get_by_id
    "useragent": result["useragent"],
                 ~~~~~~^^^^^^^^^^^^^
IndexError: No item with that key

**Comment by creasydude** [comment]
Same Problem : 
![image](https://github.com/user-attachments/assets/774255d2-0bc7-4d60-b86c-55efc1d6ca92)

**Comment by akasakaid** [comment]
> \models.py", line 76, in get_by_id
>     "useragent": result["useragent"],
>                  ~~~~~~^^^^^^^^^^^^^
> IndexError: No item with that key

https://github.com/akasakaid/blumtod/issues/55
