### ISSUE TITLE
Bot is not playing games 

### ISSUE THREAD

**Issue by ankitraz151** [akasakaid/blumtod#6]
Hey Admin ! The Blum bot is not playing game . It is only collecting farm token and starts the farm . It also claim friends income token BUT it is not playing games from ticket

**Comment by akasakaid** [comment]
> Hey Admin ! The Blum bot is not playing game . It is only collecting farm token and starts the farm . It also claim friends income token BUT it is not playing games from ticket 

Are you already read [README](#README.md) ??????

**Comment by ankitraz151** [comment]
yes admin but where is autoplay file


how to add it

**Comment by akasakaid** [comment]
![image](https://github.com/akasakaid/blumtod/assets/55008381/e1b3cc7a-e10f-4427-955b-2dbf38635af4)

Are you not see it?????

**Comment by ankitraz151** [comment]
ohh srry ,  My bad :(
