### ISSUE TITLE
Query id problem

### ISSUE THREAD

**Issue by ByBrawe** [akasakaid/blumtod#68]
if i try to get query id in console. that gave like below things.  there is no prefix that include query_id

user=%7B%22id%22%33%2C%22first_name%22%3A%3%22%2C%22last_name%22%3A%22%2232C%22username%2233A%22gasdgggas%22%2C%22language_code%22%3A%22tr%22%2C%22allows_write_to_pm%22%3Atrue%7D&chat_instance=-3&chat_type=sender&auth_date=3&hash=3

**Comment by akasakaid** [comment]
Nope, it can also be used.

**Comment by ByBrawe** [comment]
it dont work :S
![image](https://github.com/user-attachments/assets/3ebadbd0-fac6-46e6-89f8-10c7771783f3)
![image](https://github.com/user-attachments/assets/6968b523-54e3-46f6-8064-2b084143db04)

**Comment by ByBrawe** [comment]
i solved. it doesnt work on vs code. only work normal starting
