### ISSUE TITLE
Issue with proxy and worker

### ISSUE THREAD

**Issue by akashcry** [akasakaid/blumtod#74]
![image](https://github.com/user-attachments/assets/30bed9fa-389b-42f5-aba3-120d673b3636)
![image](https://github.com/user-attachments/assets/09ce3e16-671c-4f63-a293-f54c5f607016)
The proxy issue is sometimes proxy doesn't work and it closes the code. It should retry if any proxy error
And for worker error it is in the attached photo
Thank you

**Comment by akasakaid** [comment]
Try to use option number 7 (sync mode / single process). I think the problem is your device can't handle multi process.

**Comment by akashcry** [comment]
> Try to use option number 7 (sync mode / single process). I think the problem is your device can't handle multi process.

No i am running in 5 workers then also it is giving problem.
Also there is proxy problem.
If proxy doesn't respond it close the program it should try the request again

**Comment by akashcry** [comment]
> > Try to use option number 7 (sync mode / single process). I think the problem is your device can't handle multi process.
> 
> No i am running in 5 workers then also it is giving problem. Also there is proxy problem. If proxy doesn't respond it close the program it should try the request again

![image](https://github.com/user-attachments/assets/a81510c2-d6d0-48ad-8525-520749febcd3)
![image](https://github.com/user-attachments/assets/51348693-f83d-41da-ae95-0837ead3db2f)
So it Exit if proxy doesn't work.
Unless it should log error and go for next account
