### ISSUE TITLE
can you teach us how to find the auth login? (for other apps)

### ISSUE THREAD

**Issue by testpower4** [akasakaid/blumtod#77]
https://user-domain.blum.codes/api/v1/auth/provider/PROVIDER_TELEGRAM_MINI_APP

even if I used developer tools network request trace, I was not able to find this initial post request..

Thanks!

**Comment by testpower4** [comment]
don't worry, I will try wireshark etc. thanks!

**Comment by akasakaid** [comment]
To get the url you have to capture the data from the beginning, meaning from the beginning you click on the “start app” button so you can get all the existing urls.
