### ISSUE TITLE
daily checkin not working

### ISSUE THREAD

**Issue by Deku0202** [akasakaid/blumtod#80]
you need to update the url for the daily check in the payload gonna be from 420 to 300

new url 
https://game-domain.blum.codes/api/v1/daily-reward?offset=-300

please change it

**Comment by akasakaid** [comment]
> you need to update the url for the daily check in the payload gonna be from 420 to 300
> 
> new url 
> https://game-domain.blum.codes/api/v1/daily-reward?offset=-300
> 
> please change it
> 

Do you know the meaning of the number 300?

**Comment by Deku0202** [comment]
> > you need to update the url for the daily check in the payload gonna be from 420 to 300
> > new url
> > https://game-domain.blum.codes/api/v1/daily-reward?offset=-300
> > please change it
> 
> Do you know the meaning of the number 300?

Not exactly I just found that the url was changed in server request when I was checking the problem that the daily checkin is not working

**Comment by akasakaid** [comment]
> Not exactly I just found that the url was changed in server request when I was checking the problem that the daily checkin is not working

Well, I assume you don't know the meaning of the number 300 in the url parameter. So the meaning of the number 300 is the time zone you are using, in the script the bot uses my country zone where the number is 420. Why is check in not working for you when you run it? The answer is obviously because of the time difference. How is it? Do you understand?

**Comment by Deku0202** [comment]
> > Not exactly I just found that the url was changed in server request when I was checking the problem that the daily checkin is not working
> 
> Well, I assume you don't know the meaning of the number 300 in the url parameter. So the meaning of the number 300 is the time zone you are using, in the script the bot uses my country zone where the number is 420. Why is check in not working for you when you run it? The answer is obviously because of the time difference. How is it? Do you understand?

ohh i got it thanks a lot sir
