### ISSUE TITLE
bot does not work

### ISSUE THREAD

**Issue by nguyenanh29** [akasakaid/blumtod#84]
It does not work any more, errors as in the screenshot. any update needed? Thanks
![image](https://github.com/user-attachments/assets/b526e09e-8db9-49fe-a198-0b5ce160dffe)

**Comment by akasakaid** [comment]
> It does not work any more, errors as in the screenshot. any update needed? Thanks
> ![image](https://github.com/user-attachments/assets/b526e09e-8db9-49fe-a198-0b5ce160dffe)
> 

Delete database.sqlite3
