### ISSUE TITLE
Please update blum for play game

### ISSUE THREAD

**Issue by Ramo003** [akasakaid/blumtod#86]
![Uploading Screenshot_٢٠٢٤-١٠-١٢-١٢-١٦-١٤-٢٧٧_com.termux.jpg…]()

**Comment by akasakaid** [comment]
> 
> ![Uploading Screenshot_٢٠٢٤-١٠-١٢-١٢-١٦-١٤-٢٧٧_com.termux.jpg…]()
> 
> 

Ref : https://github.com/akasakaid/blumtod/issues/83#issuecomment-2408305122
