### ISSUE TITLE
Need Update?

### ISSUE THREAD

**Issue by sitxxar** [akasakaid/blumtod#88]
![image](https://github.com/user-attachments/assets/fa2429ab-730f-4903-9e7f-0f41f56cb13f)

**Comment by akasakaid** [comment]
> ![image](https://github.com/user-attachments/assets/fa2429ab-730f-4903-9e7f-0f41f56cb13f)
> 

Ref : https://github.com/akasakaid/blumtod/issues/83#issuecomment-2408305122
