### ISSUE TITLE
Cara pake auto_play_game

### ISSUE THREAD

**Issue by ssyahbandi** [akasakaid/blumtod#9]
cara pake auto play gamenya gimana bang, error
Salah penulisan kah ?

root@vultr:~/Downloads/blumtod# python3 bot.py --auto_play_game
usage: bot.py [-h] [--marinkitagawa] [--data DATA] [--proxy PROXY]
bot.py: error: unrecognized arguments: --auto_play_game

**Comment by akasakaid** [comment]
Sudah saya rubah saya mengaktifkan fitur auto play gamenya, sekarang fiturnya bisa diaktifkan di file config.json. Ubah bagian auto_play_game dari false menjadi true.

**Comment by ssyahbandi** [comment]
okei,
Thankyu ya bang, terbantu bangett
